import type { ProviderConfig } from "./types";

const RATE_LIMIT_PATTERN =
  "(?i)(rate.?limit|429 too many|usage limit|quota exceeded|context length exceeded)";

export const fallbackProviders: ProviderConfig[] = [
  {
    name: "shell",
    type: "pty",
    command: "/bin/zsh",
    args: ["-lc"],
    env: { FORCE_COLOR: "0", NO_COLOR: "1", TERM: "xterm-256color" },
    completion_pattern: "(?m)^LOOM_EXIT:\\d+\\r?$",
    input_mode: "append-arg",
    cols: 220,
    rows: 50,
    completion_timeout_ms: 120000,
    idle_timeout_ms: 30000,
    error_pattern: "",
    settle_ms: 200,
    max_output_bytes: 1048576,
  },
  {
    name: "claude-code",
    type: "pty",
    command: "claude",
    args: ["--permission-mode", "bypassPermissions"],
    env: { FORCE_COLOR: "0", NO_COLOR: "1", TERM: "xterm-256color" },
    completion_pattern: "(?m)(Task complete|Done|Finished|>\\s*$)",
    input_mode: "append-arg",
    cols: 220,
    rows: 50,
    completion_timeout_ms: 1800000,
    idle_timeout_ms: 300000,
    error_pattern: RATE_LIMIT_PATTERN,
    settle_ms: 1200,
    max_output_bytes: 2097152,
  },
  {
    name: "codex",
    type: "pty",
    command: "codex",
    args: [
      "exec",
      "--sandbox",
      "workspace-write",
      "--skip-git-repo-check",
      "--color",
      "never",
    ],
    env: { FORCE_COLOR: "0", NO_COLOR: "1", TERM: "xterm-256color" },
    completion_pattern: "(?m)(Task complete|Done|Finished)",
    input_mode: "append-arg",
    cols: 220,
    rows: 50,
    completion_timeout_ms: 1800000,
    idle_timeout_ms: 300000,
    error_pattern: RATE_LIMIT_PATTERN,
    settle_ms: 1200,
    max_output_bytes: 2097152,
  },
  {
    name: "cursor",
    type: "pty",
    command: "cursor-agent",
    args: [],
    env: { FORCE_COLOR: "0", NO_COLOR: "1", TERM: "xterm-256color" },
    completion_pattern: "(?m)(Task complete|Done|Finished|>\\s*$)",
    input_mode: "stdin",
    cols: 220,
    rows: 50,
    completion_timeout_ms: 1800000,
    idle_timeout_ms: 300000,
    error_pattern: RATE_LIMIT_PATTERN,
    settle_ms: 1200,
    max_output_bytes: 2097152,
  },
];

export type {
  ProviderConfig,
  ProviderInputMode,
  ProvidersResponse,
  PtyCompletePayload,
  PtyDataPayload,
  PtyErrorPayload,
  PtyTaskRequest,
} from "./types";
